### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by thomasmarshall**
This PR adds a favicon which will be shown in the browser tab or when someone bookmarks the Ruby documentation site. Ideally we would add a `link` tag in the HTML files, but most browsers will default to `/favicon.ico` if the `link` isn't defined, so this is easier than configuring a custom RDoc template or post-processing the files.

I copied the `favicon.ico` file directly from [ruby/www.ruby-lang.org](https://github.com/ruby/www.ruby-lang.org/blob/master/favicon.ico).

Here's an example of the bookmark I keep in my browser bookmarks bar:

| Before | After |
| - | - |
|  |  |

Perhaps this doesn't seem important, but the reason I have a bookmark is that it's currently quite difficult to reach official Ruby documentation via Google search. For example, try searching for "ruby array join" and you will see that the official Ruby docs are half way down the second page of results. As such, it would be great if the bookmark was easier to scan for visually.

### CODE REVIEW

**Review by st0012 — APPROVED** [review]

**Comment by st0012** [comment]
FWIW, I think RDoc should support customizing favicon as well. So I opened https://github.com/ruby/rdoc/issues/1192

**Comment by st0012** [comment]
Has this been deployed? Checking because https://docs.ruby-lang.org/favicon.ico still returns 404 for me.

**Comment by hsbt** [comment]
Don't rush that. I'll look that at next week.

**Comment by hsbt** [comment]
https://docs.ruby-lang.org/favicon.ico is available now.

**Pull request merged**
